services:
  mysql:
    image: mysql:8.0
    container_name: Amacre_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: amacre
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports: 
      - "3309:3306"
    volumes: 
      - amacre_mysql_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: amacre_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8083:80"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amacre_php
    restart: always
    volumes: 
      - .:/var/www/html
    ports:
      - "8001:80"

volumes:
  amacre_mysql_data:
